#########################
# Automation
#########################

# Front Door
# ==============================
- alias: "Front Door Open"
  trigger:
    platform: state
    entity_id: binary_sensor.entry_door_sensor_8_0
    from: "off"
    to: "on"
  condition:
    condition: state
    entity_id: input_boolean.door_opened
    state: "off"
  action: # SET: Entryway light on
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.door_opened
    - service: switch.turn_on
      data:
        entity_id: switch.front_door
    - service: notify.tv
      data: # NOTIFY: Android TV's: Door open
        title: "Front Door"
        message: "The front door has been opened."

- alias: "Front Door Closed"
  trigger: # IF: Entryway door closed for x seconds (August Auto-Lock Timer)
    platform: state
    entity_id: binary_sensor.entry_door_sensor_8_0
    from: "on"
    to: "off"
    for:
      seconds: !secret august_auto_lock_sec
  action: # SET: Entryway light on
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.door_opened
    - service: switch.turn_off
      data:
        entity_id: switch.front_door
    - service: notify.tv
      data: # NOTIFY: Android TV's: Door closed
        title: "Front Door"
        message: "The front door has been closed."
# ==============================

# Storage Room
# ==============================
- alias: "Storage Door Open"
  trigger:
    platform: state
    entity_id: binary_sensor.storage_door_sensor_9_0
    from: "off"
    to: "on"
  action: # SET: Storage light on
    service: switch.turn_on
    data:
      entity_id: switch.storage_room

- alias: "Storage Door Closed"
  trigger:
    platform: state
    entity_id: binary_sensor.storage_door_sensor_9_0
    from: "on"
    to: "off"
  action: # SET: Storage light off
    service: switch.turn_off
    data:
      entity_id: switch.storage_room
# ==============================

# Kitchen
# ==============================
- alias: "Kitchen Countertop at Night"
  trigger:
    platform: sun
    event: sunset
  action: # SET: Kitchen countertop lights on
    service: switch.turn_on
    data:
      entity_id: switch.kitchen_counter
# ==============================

# Input Selects
# ==============================

# Living Room
# ----------------------------------------
- alias: 'Living Room (Rainbow)'
  trigger:
    platform: state
    entity_id: input_select.living_room_scene
    to: "Rainbow"
  action:
    service: scene.turn_on
    entity_id: scene.living_room_rainbow

- alias: 'Living Room (White)'
  trigger:
    platform: state
    entity_id: input_select.living_room_scene
    to: "White"
  action:
    service: scene.turn_on
    entity_id: scene.living_room_white

- alias: 'Living Room (Relax)'
  trigger:
    platform: state
    entity_id: input_select.living_room_scene
    to: "Relax"
  action:
    service: scene.turn_on
    entity_id: scene.living_room_relax
# ----------------------------------------

# Master Bedroom
# ----------------------------------------
- alias: 'Master Bedroom (Rainbow)'
  trigger:
    platform: state
    entity_id: input_select.master_bedroom_scene
    to: "Rainbow"
  action:
    service: scene.turn_on
    entity_id: scene.master_bedroom_rainbow

- alias: 'Master Bedroom (White)'
  trigger:
    platform: state
    entity_id: input_select.master_bedroom_scene
    to: "White"
  action:
    service: scene.turn_on
    entity_id: scene.master_bedroom_white

- alias: 'Master Bedroom (Bedtime)'
  trigger:
    platform: state
    entity_id: input_select.master_bedroom_scene
    to: "Bedtime"
  action:
    service: scene.turn_on
    entity_id: scene.master_bedroom_bedtime

- alias: 'Master Bedroom (Sexy Time)'
  trigger:
    platform: state
    entity_id: input_select.master_bedroom_scene
    to: "Sexy Time"
  action:
    service: scene.turn_on
    entity_id: scene.master_bedroom_sexy_time
# ----------------------------------------

# ==============================

# Bathrooms
# ==============================

# Master Bathroom
# ------------------------------------------------------------
- alias: "Master Bathroom Motion Detected"
  trigger:
    platform: state
    entity_id: binary_sensor.master_bathroom_motion_sensor_6_0
    from: "off"
    to: "on"
  condition: # IF: Master bathroom lights are off
    condition: state
    entity_id: switch.master_bathroom
    state: "off"
    for: # IF: Lights off for x seconds
      seconds: !secret lights_off_sec
  action: # SET: Master bathroom lights on
    service: switch.turn_on
    data:
      entity_id: switch.master_bathroom
      
- alias: "Master Bathroom No Motion Detected"
  trigger:
    platform: state
    entity_id: binary_sensor.master_bathroom_motion_sensor_6_0
    from: "on"
    to: "off"
    for: # IF: No motion detected for x minutes
      minutes: !secret no_motion_min
  action: # SET: Master bathroom lights off
    service: switch.turn_off
    data:
      entity_id: switch.master_bathroom
# ------------------------------------------------------------

# Guest Bathroom
# ------------------------------------------------------------
- alias: "Guest Bathroom Motion Detected"
  trigger:
    platform: state
    entity_id: binary_sensor.guest_bathroom_motion_sensor_7_0
    from: "off"
    to: "on"
  condition: # IF: Guest bathroom lights are off
    condition: state
    entity_id: switch.guest_bathroom
    state: "off"
    for: # IF: Lights off for x seconds
      seconds: !secret lights_off_sec
  action: # SET: Guest bathroom lights on
    service: switch.turn_on
    data:
      entity_id: switch.guest_bathroom

- alias: "Guest Bathroom No Motion Detected"
  trigger:
    platform: state
    entity_id: binary_sensor.guest_bathroom_motion_sensor_7_0
    from: "on"
    to: "off"
    for: # IF: No motion detected for x minutes
      minutes: !secret no_motion_min
  action: # SET: Guest bathroom lights off
    service: switch.turn_off
    data:
      entity_id: switch.guest_bathroom
# ------------------------------------------------------------

# ==============================