#########################
# Device Trackers
#########################

- platform: netgear
  host: 10.0.0.1
  username: !secret router_user
  password: !secret router_pass
  consider_home: 900
  track_new_devices: no
  
- platform: trackr
  username: !secret trackr_user
  password: !secret trackr_pw