#########################
# Notify
#########################

# Android TV
- platform: nfandroidtv
  name: 'Living Room'
  host: 10.0.0.19

#- platform: nfandroidtv
#  name: 'Bedroom'
#  host: 10.0.0.20

- platform: group
  name: TV
  services:
    - service: living_room
    #- service: bedroom