#########################
# Remote
#########################

- platform: harmony
  name: Living Room Hub
  host: 10.0.0.25
  activity: !secret main_activity

- platform: harmony
  name: Master Bedroom Hub
  host: 10.0.0.8
  activity: !secret main_activity