#########################
# Switches
#########################

# Belkin WeMo
- platform: wemo
  
# Logitech Harmony Hub
- platform: template
  switches:
    xbox:
      friendly_name: 'Xbox One'
      value_template: '{% if states.sensor.harmony_hub.state == "Play XBox One" %}on{% else %}off{% endif %}'
      turn_on:
        service: shell_command.play_xbox_one
      turn_off:
        service: shell_command.media_center_off
    tv:
      friendly_name: 'Nexus Player'
      value_template: '{% if states.sensor.harmony_hub.state == "Watch Nexus" %}on{% else %}off{% endif %}'
      turn_on:
        service: shell_command.watch_nexus
      turn_off:
        service: shell_command.media_center_off